name: semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  # pull_request:
  #   branches: [ main ]

  # Scan all files on branches, block on any issues
  push:
    branches:
      - '**'

  # Schedule this job to run at a certain time, using cron syntax
  # Note that * is a special character in YAML so you have to quote this string
  # schedule:
  #   - cron: '30 0 1,15 * *' # scheduled for 00:30 UTC on both the 1st and 15th of the month

defaults:
  run:
    working-directory: src

jobs:
  semgrep:
    name: scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v3

      - run: semgrep ci --sarif --output=semgrep.sarif
        env:
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          SEMGREP_RULES: p/ci,p/python,p/owasp-top-ten,p/cwe-top-25 # more at semgrep.dev/explore

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
